// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/savedRecipes": {
    params: {};
  };
  "/loading": {
    params: {};
  };
  "/recipe": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/savedRecipes" | "/loading" | "/recipe" | "/*";
  };
  "routes/savedRecipes.tsx": {
    id: "routes/savedRecipes";
    page: "/savedRecipes";
  };
  "routes/loading.tsx": {
    id: "routes/loading";
    page: "/loading";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/recipe.tsx": {
    id: "routes/recipe";
    page: "/recipe";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/savedRecipes": typeof import("./src/routes/savedRecipes.tsx");
  "routes/loading": typeof import("./src/routes/loading.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/recipe": typeof import("./src/routes/recipe.tsx");
  "routes/$": typeof import("./src/routes/$.tsx");
};